version: '3.7'

services:
    dbt_image:
      image: docker.io/adovenmm/dbt-image:v0.18.1
      environment:
        DBT_PROFILES_DIR: /usr/local/dbt_profiles/
        SNOWFLAKE_LOAD_DATABASE: "RAW"
        SNOWFLAKE_TRANSFORM_WAREHOUSE: "TRANSFORM_XS"
        SNOWFLAKE_TRANSFORM_DATABASE: "ANALYTICS"
      restart: always
      command: bash -c "/bin/bash"
      working_dir: /usr/local/analytics/transform/snowflake-dbt/
      volumes:
        - type: bind
          source: .
          target: /usr/local/analytics
        - type: bind
          source: ${DBT_PROFILE_PATH}
          target: /usr/local/dbt_profiles/
          read_only: True

    data_image:
      image: docker.io/adovenmm/data-image:v01.21
      env_file:
        - .env
      restart: always
      command: bash -c "/bin/bash"
      working_dir: /usr/local/analytics/
      volumes:
        - type: bind
          source: .
          target: /usr/local/analytics

    permifrost:
      image: docker.io/adovenmm/permifrost:latest
      env_file:
        - .env
      restart: always
      command: /bin/bash -c "permifrost grant roles.yaml"
      volumes:
        - type: bind
          source: ./load/snowflake/roles.yaml
          target: /roles.yaml
          read_only: True